
configfile: "config/config.yaml"

import os
from datetime import datetime, date
import pandas as pd
import numpy as np

DATE = "032822"# str(date.today().strftime('%d%m%y'))

import re
from glob import glob

rule all:
    input:
        f"results/EMERGE_{DATE}_distillate.tsv",
        f"results/EMERGE_{DATE}_product.tsv",
        f"results/EMERGE_{DATE}_product_refined.tsv"


rule refine_product:
    input:
        "resources/pathways_refined.tsv",
        "resources/custom_input_modules/EMERGE_pathways_module.tsv",
        f"results/EMERGE_{DATE}_distillate.tsv"
    output:
        f"results/EMERGE_{DATE}_product_refined.tsv"
    threads: workflow.cores 
    shell:
       """
       python3 workflow/scripts/paths_graph_parser.py \\
           -p {input[0]} \\
           -r {input[1]} \\
           -d {input[2]} \\
               evaluate  \\
                  -o {output[0]}  \\
                  -t {threads}
       """


rule filter_distilled:
    input:
        "results/emerge_distilled/metabolism_summary.xlsx",
        'results/emerge_distilled/product.tsv',
        'resources/custom_input_modules/EMERGE_pathways_module.tsv'
    output:
        f"results/EMERGE_{DATE}_distillate.tsv",
        f"results/EMERGE_{DATE}_product.tsv"
    run:
        xl = pd.ExcelFile(input[0])
        emerge = xl.parse('EMERGE')
        prod = pd.read_csv(input[1], sep='\t')
        path = pd.read_csv(input[2], sep='\t')
        cols = ['genome'] + [f"Complex {i}: {j}" for i, j in
            zip(path['complex'].values, path['module_name'].values)]
        if not len(set(cols) - set([i for i in prod.columns])) == 0:
            raise ValueError("Your column names are wrong")
        emerge.to_csv(output[0], sep='\t', index=False)
        prod[cols].to_csv(output[1], sep='\t', index=False)


rule dram_emerge_distill:
    input:
       "results/all_annotations.tsv"
    output:
        directory("results/emerge_distilled"),
        "results/emerge_distilled/metabolism_summary.xlsx",
        'results/emerge_distilled/product.tsv'
    shell:
        """
        python3 workflow/scripts/emerge_distill_tools/distill_genomes{config[dram_to_use]}.py \\
            -i {input} \\
            -o {output[0]} \\
            --replace_forms \\
            --custom_distillate resources/custom_input_modules/EMERGE_distillate_module.tsv \\
            --custom_pathways resources/custom_input_modules/EMERGE_pathways_module.tsv
        """


rule combine_annotations:
    input:
        [i for j in config['annotations'] for i in glob(j)]
    output:
        "results/all_annotations.tsv"
    run:
        anno_dfs = [pd.read_csv(i, sep='\t', index_col=0) for i in input]
        all_annotations = pd.concat(anno_dfs)
        if not np.all([i.columns == j.columns for i in anno_dfs for j in anno_dfs]):
            raise ValueError("Something wrong with the annotations")
        all_annotations.to_csv(output[0], sep='\t')
