annotations:
  # - ./resources/test_data/min_annotations_20100900_E1D_12.tsv
  # - ./resources/test_data/min_annotations_3300023248_8.tsv
  - /home/aroneys/src/temporal_paper/data/DRAM_annotations_v2/all_annotations.tsv
dram_to_use: '1_3' # pick 1.2=1_2 or 1.3=1_3 depending on the dram you used
